repeat task.wait(10) until game:IsLoaded()
getgenv().FocusWave = 20 -- Priority limit wave
getgenv().PriorityCards = { -- Priority tags when wave = FocusWave
    "+ Enemy Speed I",
    "+ Enemy Regen I",
    "+ Yen I",
    "+ Yen II",
    "+ Yen III",
    "- Cooldown I",
    "+ Attack I",
    "+ Range I",
    "+ Gain 2 Random Effects Tier 1",
    "- Cooldown II",
    "+ Attack II",
    "+ Range II",
    "+ Gain 2 Random Effects Tier 2",
    "- Cooldown III",
    "+ Range III",
    "+ Attack III",
    "+ Gain 2 Random Effects Tier 3"
}
getgenv().Cards = { -- All cards after FocusWave wave ends
    "+ Explosive Deaths III",
    "+ Gain 2 Random Curses Tier 3",
    "+ Enemy Speed III",
    "+ Gain 2 Random Curses Tier 2",
    "+ Enemy Speed II",
    "+ Enemy Health II",
    "+ Gain 2 Random Curses Tier 1",
    "+ Enemy Health I",
    "+ Enemy Speed I",
    "+ Enemy Regen I",
    "+ Enemy Regen II",
    "+ Enemy Regen III",
    "+ Boss Damage I",
    "+ Boss Damage II",
    "+ Boss Damage III",
    "+ Yen I",
    "+ Yen II",
    "+ Yen III",
    "- Cooldown I",
    "+ Attack I",
    "+ Range I",
    "+ Gain 2 Random Effects Tier 1",
    "- Cooldown II",
    "+ Attack II",
    "+ Range II",
    "+ Gain 2 Random Effects Tier 2",
    "- Cooldown III",
    "+ Range III",
    "+ Attack III",
    "+ Gain 2 Random Effects Tier 3",
    "+ New Path"
}
-- Priority from bottom to top in all items
